### PR TITLE
feat: Enable HP ILO kernel module (both amd64 arm64)

### PR DESCRIPTION
**Pull request by halacs**
feat: Enable HP ILO kernel module (both amd64 arm64)

Signed-off-by: Gabor Nyiri <gabor.nyiri@nokia.com>

### CODE REVIEW

**Review by andrewrynhard — APPROVED** [review]

**Comment by halacs** [comment]
It seems after I filled commit body another approve is needed. Sorry and thanks!

**Comment by smira** [comment]
@halacs looks like we don't have access to the source repo:

```
remote: Permission to Nokia-DA/pkgs.git denied to talos-bot.
fatal: unable to access 'https://github.com/Nokia-DA/pkgs.git/': The requested URL returned error: 403
```

would you mind rebasing your PR yourself?

**Comment by halacs** [comment]
I hope I could rebase it successfully. I will discuss internally if we can give access to the bot.

**Comment by smira** [comment]
@halacs this looks like a merge from master vs. rebase.

(you can see two commits now from you)

if the talos-systems repo is `upstream` in your checkout, `git fetch upstream && git rebase upstream/master` should do the trick

**Comment by rgl** [comment]
This is very interesting. Can you please point me to where/how you are using this to update the BIOS settings?

**Comment by halacs** [comment]
@rgl Please check HP BIOS configuration utility at HP. There might be a REST API as well you can also use. I'm responsible for the other part of the system so I can say only this.

**Pull request merged**
