### PR TITLE
feat: add R8169 driver

### PR DESCRIPTION
**Pull request by andrewrynhard**
Adds Realtek 8169/8168/8101/8125 ethernet support.

Signed-off-by: Andrew Rynhard <andrew@rynhard.io>

### CODE REVIEW

**Review by Ulexus — APPROVED** [review]

**Comment by Ulexus** [comment]
My thought is that this chip is vastly less-used on ARM, but there is no real reason to make the configs more different than they have to be. :+1:

**Comment by andrewrynhard** [comment]
> My thought is that this chip is vastly less-used on ARM, but there is no real reason to make the configs more different than they have to be.

Oh totally agree. Yeah the strategy thusfar has been to try to keep them in sync as much as we can.

**Pull request merged**
