### PR TITLE
feat: add mdraid 1/0/10

### PR DESCRIPTION
**Pull request by sergelogvinov**
It helps to use soft raid as second (data) drive.

Very useful for GCP local SSDs or Equinix Metal.

RAID 0/1/10 does not affect boot time.

### CODE REVIEW

**Comment by smira** [comment]
Just curious, how is it supposed to be used with Talos?

**Comment by sergelogvinov** [comment]
It helps csi to create/prepare/mount soft raid to the pod

As talos already has lvm kernel support.

**Comment by smira** [comment]
So it's not about Talos system disk, but rather about additional disks and volume provisioners, got it.

**Review by smira — APPROVED** [review]

**Pull request merged**
